### PR TITLE
Add support for Golang

### PR DESCRIPTION
**Pull request by AyoubEd**
**Added support for Golang**

Since Golang is starting to be used more and more in CP landscape, I thought I'll add support for it. Also, It's a way to encourage people to start using it.

### CODE REVIEW

**Comment by chermehdi** [comment]
For future reference, it would be good if you can add a description of why you though your change would be good if it's not on the issue list :)

**Comment by Eroui** [comment]
Link PR to an issue please.

**Comment by AyoubEd** [comment]
@chermehdi Thank you. I'll keep that in mind.

**Comment by chermehdi** [comment]
I am going to decline your PR because you pushed to master directly, the PR should be opened from another feature branch. you will have to create another branch and put your code in it. and then push and create a PR. and before that create an issue and refere to it in the branch name and the commit message :)

**Pull request closed without merging**
